apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: rag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: rag-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: GROQ_API_KEY
          valueFrom:
            secretKeyRef:
              name: groq-secret
              key: api-key
        - name: QDRANT_HOST
          value: "qdrant-service"
        - name: QDRANT_PORT
          value: "6333"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: rag
spec:
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
    resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"